/**
 * Created by stepan on 20/04/17.
 */

public class WebserviceTypes{
    public class AccountJSONParameters{
        public String vlocityCmtVCustomerPriority;
        public String accountNumber;
        public String accountStatus;
        public String roleType;
        public String billingCity;
        public String billingPostalCode;
        public String billingState;
        public String billingCountry;
        public String vlocityCmtPremisesIdentifier;
        public String vlocityCmtBillingEmailAddress;
        public String phone;
        public String vlocityCmtPartyId;
        public String languageAbility;
        public String name;
        public String lastName;
        public String firstName;
        public String Salutation;
        public String uniqueBillSpecID;
        public String billFormatID;
        public String paperlessBilling;
        public String billingDate;
        public String billingPeriodName;
    }
}